### ISSUE TITLE
Problem updating venv for v4.4.7 on first compile

### ISSUE THREAD

**Issue by ccrause** [michael-ring/espsdk4fpc#10]
When testing v4.4.7 I get the error below on first compile, when the venv goes through its update process.  Replacing this venv with a normal one generated by esp-idf v4.4.7 works, not sure what is different though.
```
Debug: Collecting construct==2.10.54 (from -r /home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/requirements.txt (line 49))
Debug:   Using cached construct-2.10.54.tar.gz (55 kB)
Debug:   Installing build dependencies: started
Debug:   Installing build dependencies: finished with status 'done'
Debug:   Getting requirements to build wheel: started
Debug:   Getting requirements to build wheel: finished with status 'done'
Debug:   Installing backend dependencies: started
Debug:   Installing backend dependencies: finished with status 'done'
Debug:   Preparing metadata (pyproject.toml): started
Debug:   Preparing metadata (pyproject.toml): finished with status 'done'
Debug: Collecting Flask<1.0,>=0.12.2 (from gdbgui==0.13.2.0->-r /home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/requirements.txt (line 26))
Debug:   Using cached Flask-0.12.5-py2.py3-none-any.whl.metadata (2.0 kB)
Debug: Collecting Flask-Compress<2.0,>=1.4.0 (from gdbgui==0.13.2.0->-r /home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/requirements.txt (line 26))
Debug:   Using cached Flask_Compress-1.15-py3-none-any.whl.metadata (8.4 kB)
Debug: Collecting Flask-SocketIO<3.0,>=2.9 (from gdbgui==0.13.2.0->-r /home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/requirements.txt (line 26))
Debug:   Using cached Flask_SocketIO-2.9.6-py2.py3-none-any.whl.metadata (873 bytes)
Debug: Collecting gevent<2.0,>=1.2.2 (from gdbgui==0.13.2.0->-r /home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/requirements.txt (line 26))
Debug:   Using cached gevent-1.5.0.tar.gz (5.3 MB)
Debug:   Installing build dependencies: started
Debug:   Installing build dependencies: finished with status 'done'
Debug:   Getting requirements to build wheel: started
Debug:   Getting requirements to build wheel: finished with status 'error'
Debug:   error: subprocess-exited-with-error
Debug:   
Debug:   × Getting requirements to build wheel did not run successfully.
Debug:   │ exit code: 1
Debug:   ╰─> [315 lines of output]
Debug:       Compiling src/gevent/resolver/cares.pyx because it changed.
Debug:       [1/1] Cythonizing src/gevent/resolver/cares.pyx
Debug:       performance hint: src/gevent/libev/corecext.pyx:1291:5: Exception check on '_syserr_cb' will always require the GIL to be acquired.
Debug:       Possible solutions:
Debug:           1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
Debug:           2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.
Debug:       warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
Debug:       warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
Debug:       warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
Debug:       warning: src/gevent/libev/corecext.pyx:1288:0: Global name __SYSERR_CALLBACK matched from within class scope in contradiction to to Python 'class private name' rules. This may change in a future release.
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:               if events & ~(libev.EV__IOFDSET | libev.EV_READ | libev.EV_WRITE):
Debug:                   raise ValueError('illegal event mask: %r' % events)
Debug:               # All the vfd_functions are no-ops on POSIX
Debug:               cdef int vfd = libev.vfd_open(fd)
Debug:               libev.ev_io_init(&self._watcher, <void *>gevent_callback_io, vfd, events)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1027:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:                   raise ValueError('illegal event mask: %r' % events)
Debug:               # All the vfd_functions are no-ops on POSIX
Debug:               cdef int vfd = libev.vfd_open(fd)
Debug:               libev.ev_io_init(&self._watcher, <void *>gevent_callback_io, vfd, events)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &io_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1028:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:       
Debug:           def __cinit__(self, loop loop, double after=0.0, double repeat=0.0, ref=True, priority=None):
Debug:               if repeat < 0.0:
Debug:                   raise ValueError("repeat must be positive or zero: %r" % repeat)
Debug:               libev.ev_timer_init(&self._watcher, <void *>gevent_callback_timer, after, repeat)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1072:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:           def __cinit__(self, loop loop, double after=0.0, double repeat=0.0, ref=True, priority=None):
Debug:               if repeat < 0.0:
Debug:                   raise ValueError("repeat must be positive or zero: %r" % repeat)
Debug:               libev.ev_timer_init(&self._watcher, <void *>gevent_callback_timer, after, repeat)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &timer_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1073:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:               # 1) "libev: ev_signal_start called with illegal signal number"
Debug:               #    EV_NSIG might be different from signal.NSIG on some platforms
Debug:               # 2) "libev: a signal must not be attached to two different loops"
Debug:               #    we probably could check that in LIBEV_EMBED mode, but not in general
Debug:               libev.ev_signal_init(&self._watcher, <void *>gevent_callback_signal, signalnum)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1117:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:               #    EV_NSIG might be different from signal.NSIG on some platforms
Debug:               # 2) "libev: a signal must not be attached to two different loops"
Debug:               #    we probably could check that in LIBEV_EMBED mode, but not in general
Debug:               libev.ev_signal_init(&self._watcher, <void *>gevent_callback_signal, signalnum)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &signal_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1118:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:       
Debug:           cdef libev.ev_idle _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_idle_init(&self._watcher, <void*>gevent_callback_idle)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1133:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:           cdef libev.ev_idle _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_idle_init(&self._watcher, <void*>gevent_callback_idle)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &idle_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1134:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:       
Debug:           cdef libev.ev_prepare _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_prepare_init(&self._watcher, <void*>gevent_callback_prepare)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1146:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:           cdef libev.ev_prepare _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_prepare_init(&self._watcher, <void*>gevent_callback_prepare)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &prepare_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1147:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:       
Debug:           cdef libev.ev_check _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_check_init(&self._watcher, <void*>gevent_callback_check)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1159:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:           cdef libev.ev_check _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_check_init(&self._watcher, <void*>gevent_callback_check)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &check_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1160:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:       
Debug:           cdef libev.ev_fork _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_fork_init(&self._watcher, <void*>gevent_callback_fork)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1172:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:           cdef libev.ev_fork _watcher
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_fork_init(&self._watcher, <void*>gevent_callback_fork)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &fork_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1173:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:               # Note the use of ev_async_pending instead of ev_is_pending
Debug:               return True if libev.ev_async_pending(&self._watcher) else False
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_async_init(&self._watcher, <void*>gevent_callback_async)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1189:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:               return True if libev.ev_async_pending(&self._watcher) else False
Debug:       
Debug:           def __cinit__(self, loop loop, ref=True, priority=None):
Debug:               libev.ev_async_init(&self._watcher, <void*>gevent_callback_async)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &async_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1190:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:                   raise AttributeError("Child watchers are not supported on Windows")
Debug:               if not loop.default:
Debug:                   raise TypeError('child watchers are only available on the default loop')
Debug:               libev.gevent_install_sigchld_handler()
Debug:               libev.ev_child_init(&self._watcher, <void *>gevent_callback_child, pid, trace)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1212:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:               if not loop.default:
Debug:                   raise TypeError('child watchers are only available on the default loop')
Debug:               libev.gevent_install_sigchld_handler()
Debug:               libev.ev_child_init(&self._watcher, <void *>gevent_callback_child, pid, trace)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &child_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1213:20: Cannot convert 'start_and_stop *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:                   self._paths = paths
Debug:               else:
Debug:                   paths = <bytes>path
Debug:                   self._paths = paths
Debug:               libev.ev_stat_init(&self._watcher, <void *>gevent_callback_stat, <char*>paths, interval)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:                                ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1263:25: Cannot convert 'ev_watcher *' to Python object
Debug:       
Debug:       Error compiling Cython file:
Debug:       ------------------------------------------------------------
Debug:       ...
Debug:               else:
Debug:                   paths = <bytes>path
Debug:                   self._paths = paths
Debug:               libev.ev_stat_init(&self._watcher, <void *>gevent_callback_stat, <char*>paths, interval)
Debug:               self.__watcher = <libev.ev_watcher*>&self._watcher
Debug:               self.__ss = &stat_ss
Debug:                           ^
Debug:       ------------------------------------------------------------
Debug:       
Debug:       src/gevent/libev/corecext.pyx:1264:20: Cannot convert 'start_and_stop *' to Python object
Debug:       Compiling src/gevent/libev/corecext.pyx because it changed.
Debug:       [1/1] Cythonizing src/gevent/libev/corecext.pyx
Debug:       Traceback (most recent call last):
Debug:         File "/home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
Debug:           main()
Debug:         File "/home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
Debug:           json_out['return_val'] = hook(**hook_input['kwargs'])
Debug:         File "/home/christo/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
Debug:           return hook(config_settings)
Debug:         File "/tmp/pip-build-env-xav8p1n5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
Debug:           return self._get_build_requires(config_settings, requirements=['wheel'])
Debug:         File "/tmp/pip-build-env-xav8p1n5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
Debug:           self.run_setup()
Debug:         File "/tmp/pip-build-env-xav8p1n5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
Debug:           super().run_setup(setup_script=setup_script)
Debug:         File "/tmp/pip-build-env-xav8p1n5/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
Debug:           exec(code, locals())
Debug:         File "<string>", line 49, in <module>
Debug:         File "/tmp/pip-install-yvj53ne_/gevent_bdd003825fa041bbb14e48662be4af24/_setuputils.py", line 254, in cythonize1
Debug:           new_ext = cythonize(
Debug:         File "/tmp/pip-build-env-xav8p1n5/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
Debug:           cythonize_one(*args)
Debug:         File "/tmp/pip-build-env-xav8p1n5/overlay/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
Debug:           raise CompileError(None, pyx_file)
Debug:       Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
Debug:       [end of output]
Debug:   
Debug:   note: This error originates from a subprocess, and is likely not a problem with pip.
Error: error: subprocess-exited-with-error
Debug: 
Error: × Getting requirements to build wheel did not run successfully.
Error: │ exit code: 1
Error: ╰─> See above for output.
Debug: 
Error: note: This error originates from a subprocess, and is likely not a problem with pip.
Debug: Setting up modules for venv failed
```

**Comment by michael-ring** [comment]
Feels like python version does not play nice with the dependencies, can you please do

ls -l in the bin directory of both venv versions and check which python version is linked?
perhaps I will also go back to my workarround from before as we only need the dependencies for esptool and ldconf, which will be a lot less than all the stuff that is needed for the other tools...

(base) tgdrimi9@macbookpro14 bin $ ls -l python*
lrwxr-xr-x  1 tgdrimi9  staff   7 15 Apr 17:37 python -> python3
lrwxr-xr-x  1 tgdrimi9  staff  38 15 Apr 17:37 python3 -> /Users/tgdrimi9/miniconda3/bin/python3
lrwxr-xr-x  1 tgdrimi9  staff   7 15 Apr 17:37 python3.11 -> python3
(base) tgdrimi9@macbookpro14 bin $ pwd
/Users/tgdrimi9/devel/uuidgenerator/venv/bin

**Comment by michael-ring** [comment]
Is ldgen.py still called during build? could not find an entry in my fpcdebug.txt file

**Comment by ccrause** [comment]
The version that works:
~/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/venv-works/bin$ ls -l python*
lrwxrwxrwx 1 christo christo 15 May 22 18:18 python -> /usr/bin/python
lrwxrwxrwx 1 christo christo  6 May 22 18:18 python3 -> python
lrwxrwxrwx 1 christo christo  6 May 22 18:18 python3.10 -> python

$ /usr/bin/python --version
Python 3.10.12

The version generated by buildsdk.sh:
:~/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/venv/bin$ ls -l python*
lrwxrwxrwx 1 christo christo  7 May 22 18:22 python -> python3
lrwxrwxrwx 1 christo christo 46 May 22 18:22 python3 -> /home/christo/espsdk4fpc2/venv-idf/bin/python3
lrwxrwxrwx 1 christo christo  7 May 22 18:22 python3.10 -> python3

~/espsdk4fpc2/4.4.7/esp32c3/riscv32-binutils-amd64-linux/esp-idf-4.4.7/venv/bin/python3 --version
Python 3.10.12

**Comment by ccrause** [comment]
> Is ldgen.py still called during build? could not find an entry in my fpcdebug.txt file

It is used in v4.4.7 and v5.0.6. It is an integral part of generating a linker script out of all the fragments and config options.  ldgen.py is used to produce the sections.ld file.

**Comment by michael-ring** [comment]
Fixed along the way by reducing dependencies to a minimum
